experiment_name: debug
data_params:
  timesteps:
    start: 0
    end: 20
  zstacks:
    start: 20
    end: 80
  dataset_name: mitospace
  data_path: /home/dhruvagarwal/projects/MitoSpace4D/data/dummy_data
  patch_size: 256
  samples_per_drug: None
  transforms:
      ResizedCrop:
        p: 0.5
        size: 256
        scale: [0.35, 1.0]
      Brightness:
        p: 0.0
        val: 0.3
      HorizontalFlip:
        p: 0.5
      VerticalFlip:
        p: 0.5
      GaussianNoise:
        p: 0.3
        mu: 0.0
        scale: 0.001
      GaussianBlur:
        p: 0.5
        sigma: 1.0
        kernel_size: 5
      RandomErasing:
        p: 0.3
        scale: [0.02, 0.2]
        ratio: [0.3, 3.3]
  filters: null
logging_params:
  save_path: /home/dhruvagarwal/projects/MitoSpace4D/runs
model_params:
  arch: resnet18
  pretrained: false
  out_dim: 512
  in_channels: 2
  num_z: 60
  timesteps: 20
training:
  loss:
    name: InfoNCELoss
    use_normalization: True
    temperature: 0.07
  max_epochs: 300
  print_interval: 85
  projector_interval: 1000000000000000000000000000000000000000000000000000000000000000000000000000000000000000
  batch_size: 4
  training_samples: None
  ckpt_callback:
    monitor: Val/loss
    mode: min
    save_top_k: 1
    save_last: True
  continue_from_ckpt_wo_opt: None
  lr: 0.0003
  weight_decay: 0.00001
  workers: 1
  prefetch_factor: 2
  persistent_workers: True
  n_views: 2
distributed:
  flag: True
  num_gpus: -1
  accelerator: gpu
  strategy: ddp
  num_nodes: 1
evaluate:
  top_ns: [1, 3]
  dataset: Cal27
