apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - name: gpu-container
    image: drvagwl1008/mitospace4d:latest
    command: ["sleep", "infinity"]
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1

    volumeMounts:
      - name: pvc-storage
        mountPath: /mitospace4d-vol-2

  volumes:
    - name: pvc-storage
      persistentVolumeClaim:
        claimName: mitospace4d-vol-2