apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mitospace4d-vol
spec:
  storageClassName: rook-cephfs-central
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 15000Gi