apiVersion: batch/v1
kind: Job
metadata:
  name: reduce-data-9
spec:
  template:
    spec:
      initContainers:
      - name: init-clone-repo
        image: alpine/git
        env:
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: user
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: gitlab-secret
              key: password
        command: ["/bin/sh", "-c"]
        args:
          - git clone --single-branch --branch gpu_augmentation_30z_int8 https://$(GIT_USERNAME):$(GIT_PASSWORD)@gitlab.nrp-nautilus.io/drvagwl1008/mitospace4d.git /opt/repo/mitospace4d
        volumeMounts:
          - name: git-repo
            mountPath: /opt/repo

      containers:
      - name: reduce-data
        image: drvagwl1008/mitospace4d:latest
        command:
          - /bin/sh
        args:
          - -c
          - python /opt/repo/mitospace4d/dumps/reduce_data.py
        volumeMounts:
        - name: git-repo
          mountPath: /opt/repo
        - name: mitospace4d-vol
          mountPath: /mitospace4d-vol
        - name: mitospace4d-vol-3
          mountPath: /mitospace4d-vol-3

        resources:
          limits:
            memory: "128Gi"
            cpu: "64"
          requests:
            memory: "128Gi"
            cpu: "64"

      volumes:
      - name: git-repo
        emptyDir: {}
      - name: mitospace4d-vol
        persistentVolumeClaim:
          claimName: mitospace4d-vol
      - name: mitospace4d-vol-3
        persistentVolumeClaim:
          claimName: mitospace4d-vol-3

      restartPolicy: Never
  backoffLimit: 0
