model:
  input_dims: [1, 64, 256, 256]
  latent_dim: 2
data:
  manifest_path: "/mnt/aquila/ssd_processing/Others/MitoSpace4D/2024v3_data/processed_data/"
  val_split: 0.1
  seed: 1123
  num_workers: 4
  channel_index: None
  prefetch_factor: 4
  n_samples: null
training:
  batch_size: 4
  grad_acc_steps: 32
  epochs: 100
  lr: 0.001
  min_lr: 0.000001
  weight_decay: 0.0001
logging:
  wandb_project: "mitospace-ae"
  run_name: "2024v3_ft_sequence-norm"
  run_dir: "./runs/"
  log_interval: 10
  save_interval: 5
  num_images: 3
